# Generated by Django 5.0.4 on 2024-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('order_comment', models.TextField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_zip', models.CharField(blank=True, max_length=12, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
