# Generated by Django 5.0.4 on 2024-05-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('order_comment', models.TextField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_zip', models.CharField(blank=True, max_length=12, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('rebate_quantity', models.IntegerField()),
                ('rebate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upsell_product_id', models.IntegerField()),
                ('amount_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalLinePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rebatePercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('giftwrapping', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='webshopapp.order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopapp.product')),
            ],
        ),
    ]
